name: Toke-N-Smoke
version: '1.0'
main: me.oscarcusick.tokensmoke.Toke_N_Smoke
api-version: '1.20'
commands:
  FreshPack:
    description: "Spawns a fresh pack of cigarettes"
    usage: "/FreshPack <Tier>"
    permission: op
  Drug:
    description: "Gives the player whatever drug for debugging purposes"
    usage: "/Drug <Name>"
    permission: op
  GetWeedSeeds:
    description: "Gives the player weed seeds"
    usage: "/GetWeedSeeds <Tier>"
    permission: op
  GetOpiumSeeds:
    description: "Gives the player opium seeds"
    usage: "/GetWeedSeeds"
    permission: op